name: Sync Fork

on:
  push:
    branches:
    - master
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.FORK_TOKEN }}
          owner: AcmeProject
          base: master
          head: master
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: giltene/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package --file pom.xml
      
    - run: mkdir -p path/to/artifact
    - run: cat "./target/WildTP.jar" > path/to/artifact/WildTP.jar
    - uses: actions/upload-artifact@master
      with:
        name: WildernessTp
        path: path/to/artifact
